# =============================================================================
# Deck .NET版本配置文件
# =============================================================================
# 此文件控制Deck工具的所有配置选项
# 更多信息请参考: https://github.com/chatterzhao/deck
# =============================================================================

templates:
  repository:
    url: https://github.com/chatterzhao/deck-templates.git
    branch: main
    fallback_url: https://gitee.com/zhaoquan/deck-templates.git
  auto_update: true
  cache_expire: 24h
  update_on_start: true
container:
  engine: podman
  auto_install: true
  check_on_start: true
  fallback_engine: docker
network:
  proxy:
    http: ''
    https: ''
    no_proxy: localhost,127.0.0.1
  d_n_s:
  - 8.8.8.8
  - 1.1.1.1
  mirrors:
    docker_registry: docker.m.daocloud.io
    apt_mirror: mirrors.ustc.edu.cn
project:
  name: test-config
  workspace_path: /workspace
  auto_create_gitignore: true
cache:
  enable_build_cache: true
  cache_directory: .deck/cache
  max_cache_size: 5GB
  auto_cleanup: true
  cleanup_days: 30
u_i:
  language: zh-CN
  show_tips: true
  interactive_mode: true
  show_podman_commands: true
development:
  auto_port_forward: true
  default_memory_limit: 4g
  default_cpu_limit: 2
  enable_hot_reload: true
  show_build_output: true
security:
  enable_no_new_privileges: true
  restricted_capabilities: true
  scan_templates: false
logging:
  level: info
  file: .deck/logs/deck.log
  max_file_size: 10MB
  keep_files: 5
