version: '3.8'

services:
  dotnet${DOTNET_VERSION_NAME}:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY:-docker.m.daocloud.io}
        UBUNTU_VERSION: ${UBUNTU_VERSION:-22.04}
        UBUNTU_NAME: ${UBUNTU_NAME:-2204}
        DOTNET_VERSION: ${DOTNET_VERSION:-9.0}
        DOTNET_VERSION_NAME: ${DOTNET_VERSION_NAME:-90}
        DEPENDENCIES: ${DEPENDENCIES:-"curl git wget build-essential ca-certificates"}
        INSTALL_ANDROID_SUPPORT: ${INSTALL_ANDROID_SUPPORT:-false}
        INSTALL_WASM_TOOLS: ${INSTALL_WASM_TOOLS:-true}
        INSTALL_WASM_EXPERIMENTAL: ${INSTALL_WASM_EXPERIMENTAL:-false}
        INSTALL_WASI_EXPERIMENTAL: ${INSTALL_WASI_EXPERIMENTAL:-false}
        INSTALL_DOTNET_WATCH: ${INSTALL_DOTNET_WATCH:-true}
        INSTALL_DOTNET_FORMAT: ${INSTALL_DOTNET_FORMAT:-true}
        INSTALL_DOTNET_EF: ${INSTALL_DOTNET_EF:-false}
        INSTALL_DOTNET_OUTDATED: ${INSTALL_DOTNET_OUTDATED:-false}
        INSTALL_DOTNET_TRACE: ${INSTALL_DOTNET_TRACE:-false}
        INSTALL_DOTNET_SERVE: ${INSTALL_DOTNET_SERVE:-false}
    image: localhost/dotnet${DOTNET_VERSION_NAME}:${DOTNET_VERSION:-9.0}
    container_name: ${PROJECT_NAME:-dotnet}${DOTNET_VERSION_NAME}
    hostname: ${PROJECT_NAME:-dotnet}${DOTNET_VERSION_NAME}
    volumes:
      # Mount project workspace (relative to project root)
      - ../../../:${WORKSPACE_PATH:-/workspace}
      # Persistent cache volumes for faster rebuilds
      # Ubuntu基础层缓存 (来自下层Ubuntu基础镜像)
      - type: volume
        source: apt-cache
        target: /var/cache/apt
      - type: volume
        source: apt-lib-cache
        target: /var/lib/apt
      # .NET特定缓存 (当前层新增)
      - type: volume
        source: nuget-cache
        target: ${NUGET_PACKAGES:-/opt/nuget-cache}
      - type: volume
        source: dotnet-tools-cache
        target: /root/.dotnet/tools
    ports:
      # Development server ports (runtime configurable)
      - "${DEV_PORT:-5000}:5000"
      - "${DEBUG_PORT:-9229}:9229"
      # Web development ports
      - "${WEB_PORT:-8080}:8080"
      - "${HTTPS_PORT:-8443}:8443"
    env_file:
      # Load all environment variables from .env
      - .env
    environment:
      # Override specific runtime variables if needed
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT:-Development}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - PROJECT_NAME=${PROJECT_NAME:-dotnet}${DOTNET_VERSION_NAME}
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_NOLOGO=1
      - DOTNET_USE_POLLING_FILE_WATCHER=${DOTNET_USE_POLLING_FILE_WATCHER:-true}
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=${DOTNET_WATCH_RESTART_ON_RUDE_EDIT:-true}
    working_dir: ${WORKSPACE_PATH:-/workspace}
    command: /usr/local/bin/dotnet${DOTNET_VERSION_NAME}
    stdin_open: true
    tty: true
    # Resource limits (runtime configurable)
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-4g}
          cpus: '${CPU_LIMIT:-2}'
        reservations:
          memory: 1g
          cpus: '0.5'
    shm_size: ${SHM_SIZE:-512m}
    # Network configuration
    network_mode: bridge
    # DNS configuration for better network performance
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # Health check to ensure container is working
    healthcheck:
      test: ["CMD", "dotnet", "--info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Restart policy
    restart: unless-stopped
    # Security options
    security_opt:
      - no-new-privileges:true
    # Enable development features
    cap_add:
      - SYS_PTRACE  # For debugging with .NET debugger

volumes:
  apt-cache:
    driver: local
  apt-lib-cache:
    driver: local
  nuget-cache:
    driver: local
  dotnet-tools-cache:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16